networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.211.1.0/24
version: '3'
services:
  web:
    image: todo-image:test
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      my_custom_network:
        ipv4_address: 172.211.1.2
